### ISSUE TITLE
Strings Assigned by SDK Cause Crash When Overridden by Engine

### ISSUE THREAD

**Issue by mopioid** [bl-sdk/PythonSDK#45] opened 2019-06-04 08:24 UTC
When assigning strings to objects' properties using the SDK, the results are as expected, and the changes appear in game as desired:

```Python
namePart = bl2sdk.FindObject(
    "ItemNamePartDefinition",
    "GD_ClassMods.Prefix_Assassin.Prefix_Infiltrator_00_Infiltrator"
)
namePart.PartName = "Infilbooper"
```

However, when the same property is subsequently altered elsewhere in the engine (specifically via a `set` console command), it triggers a crash:

```Python
bl2sdk.GetEngine().GamePlayers[0].Actor.ConsoleCommand(
    "set GD_ClassMods.Prefix_Assassin.Prefix_Infiltrator_00_Infiltrator PartName Infiltrator",
    0
)
```

**Comment by apple1417** [comment] 2021-02-04 03:54
Duplicate of #28

**Closed as completed by apple1417** 2021-02-04 03:54 UTC
