### ISSUE TITLE
Language&Encoding Problem

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [bl-sdk/PythonSDK#79] opened 2021-01-27 09:23 UTC
Hi, i am a player who use Simplified Chinese Language 
There is a problem when adding pythonSDK to borderlands 2

[Main Menu](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/mainmenu.png)
[Mod Control Settings](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/ModdedControlSettings.png)
[Keyboard Control Settings](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/KeyboardControlSettings.png)

**Comment by apple1417** [comment] 2021-02-04 03:51
Duplicate of #76

**Closed as completed by apple1417** 2021-02-04 03:51 UTC
