### ISSUE TITLE
Mod Options and Keyboard Binds menu not working Proton 5.0-10 Arch Linux x86_64 5.10.13-zen1-2-zen 

### ISSUE THREAD

**Issue by mjctechguy** [bl-sdk/PythonSDK#83] opened 2021-02-07 22:43 UTC
System info: Arch Linux x86_64 5.10.13-zen1-2-zen 
Proton Version: **5.0-10** Also tested with **Proton-GE-5.21**
Issue: When trying to edit mod settings and keybinds through in-built menu, clicking/hovering on the links does nothing

Latest Python-SDK is installed 0.7.8
![image](https://user-images.githubusercontent.com/1353993/107161452-beacbd00-6994-11eb-875b-29cd1c46a9af.png)
![image](https://user-images.githubusercontent.com/1353993/107161460-cc624280-6994-11eb-9db4-76a14cf3140b.png)
![image](https://user-images.githubusercontent.com/1353993/107161490-eef45b80-6994-11eb-9af5-5a5cec100201.png)

Tested with only default mods installed no extras, enabled Borderlands 2 Map Reloader for keybinds and Backpack Manager for mod options. When hovering or clicking on the button error messages are output to python-sdk.log. 
> At:
  Z:\home\michael\.local\share\Steam\steamapps\common\Borderlands 2\Binaries\Win32\Mods\ModMenu\KeybindManager.py(231): _HandleSelectionChangeRollover
SystemError: <built-in method __next__ of PyCapsule object at 0x16CEB320> returned NULL without setting an error

>At:
  Z:\home\michael\.local\share\Steam\steamapps\common\Borderlands 2\Binaries\Win32\Mods\ModMenu\OptionManager.py(101): _WillowScrollingListOnClikEvent
SystemError: <built-in method __next__ of PyCapsule object at 0x16CEB320> returned NULL without setting an error

[Full python-sdk.log](https://github.com/bl-sdk/PythonSDK/files/5940184/python-sdk.log)

**Comment by Jabbermuggel** [comment] 2021-09-19 14:52
I can reproduce the issue. I'm also on arch, using Proton 5.13-6. From what I can gather this error occurs when trying to iterate over an `unrealsdk.FArray`-Object. This fortunately doesn't seem to occur too often in the mod loading, but it does in the functions `_WillowScrollingListOnClikEvent` in OptionManager.py and `_HandleSelectionChangeRollover` in KeybindManager.py which causes the errors. 

I managed to rewrite the first function somewhat so it kinda works for me now, but haven't managed the keybinds. However, it seems more practical to just modify the settings.ini-files of the respective mods, they work regardless.

On a side note the same error happens in the [Commander-Mod](https://github.com/mopioid/Borderlands-Commander) on load, so you have to patch the damage number feature out to even get it to load.

**Comment by UndeadBulwark** [comment] 2022-02-14 08:11
Is there a fix for this?

**Comment by Jabbermuggel** [comment] 2022-02-14 19:10
Unfortunately I wasn't able to find a fix. For some reason these FArray-Objects don't get passed correctly by the game engine. Since this issue occurs when calling quite different functions (e.g. the damage number generators in the Commander Mod example or keybind lists) I suspect some sort of general issue with unreal engine (plugins) in proton (also just tried again with the current proton-ge-custom, no luck though). The only way to mitigate the issue was just disabling any code using problematic functions, which does rather limit certain mods.

**Comment by egoarka** [comment] 2022-07-06 16:10
I found a way to silence this error by patching python dll. (it looks like sanity check, but if we ignore it, it does not break execution flow)

Code below is working with python sdk, v0.7.10
```
with open("python37.dll", 'r+b') as f:
    f.seek(0xdad78) # seek to `_Py_CheckFunctionResult + 0x16` 
    f.write(b'\xeb') # replace jne to jmp
```

I tested it with multiple mods, it's working fine without any issues.

**Comment by Jabbermuggel** [comment] 2022-07-08 12:28
I just tested this with my game and it seems to work just as intended now. Thank you very much, I'd never have found such a fix in a million years. Maybe the `README.md` could be updated to mention this as a possible workaround?

**Closed as completed** 2022-07-16 08:01 UTC
